### ISSUE TITLE
YouTube ID Variable

### ISSUE THREAD

**Issue by KeironLowe92** [vector/Antenna#28]
Would it be possible to have a variable for the YouTube Video ID? I was building a site recently that I would have liked to use Antenna on and it was using the YouTube API to generate the iFrames rather then having them all load on page load.

**Comment by mrw** [comment]
That's not something currently in Antenna but is definitely possible. However, for your use case have you tried also setting `youtube_enablejsapi=1` as a parameter? It enables the API and may give you what you need!

**Comment by KeironLowe92** [comment]
I actually modified Antenna to do this, if your happy with adding this I'll submit a PR when I get a chance. 

I have used that parameter previously although in this case, I needed to generate the videos on the fly, rather than load a lot of iFrames straight away. Cheers anyway though!

**Comment by mrw** [comment]
A PR would be great, thanks!

**Comment by mrw** [comment]
Closing; this was added some time ago as {video_id}.
