### ISSUE TITLE
fall back to lower res thumbnail

### ISSUE THREAD

**Issue by kdesigns** [vector/Antenna#29]
When I include a thumbnail on a page I would usually want the highest resolution, so I use `{video_highres}`.

However, I noticed that a lot of videos don't have that resolution and then YouTube served some kind of very very low res default crappy thumbnail.

Even when I use `{video_mediumres}` YT often serves the crappy default thumbnail.

So now I set every video to use the `{video_thumbnail}` because there is no way to check when it serves which version.

It would be nice to have this add-on doe that automatically by checking the width/height of the image returned, and if it falls within the threshold of the high/medium/default res thumbnails.

**Comment by mrw** [comment]
Thanks for the feature request! I can't see us implementing this soon, but we'll definitely keep it in mind. If you end up writing this logic then feel free to make a pull request and we'll consider merging it!
