### ISSUE TITLE
Vimeo Video Not Displaying

### ISSUE THREAD

**Issue by ashleymarchant** [vector/Antenna#30]
We would like to use Antenna to display private videos from Vimeo. The videos are set to only be visible on one URL. We have used the module successfully many times with private vimeo videos, however they are not showing up on this site using the following code:

 `{exp:antenna url="{video_url}" max_width="500" max_height="380"}
           {embed_code}    
       {/exp:antenna}`

When I put the URL in the code manually (replacing the {video_url} with a vimeo link) I can see the player. 
We are using EE 2.11.7
Please advise. 

Thank you.

**Comment by mrw** [comment]
This is almost definitely a parse order issue. You may want to add something like `parse="inward"` to whatever tag is outputting the `video_url`. If antenna is working with a hardcoded URL it means something before/above it isn't parsing the tag into a URL correctly.

**Comment by ashleymarchant** [comment]
Hi, thank you. We are just using a simple channel entries call to output the field. When I just simply put the field in the template (without antenna code around it) it shows the correct vimeo url.

**Comment by mrw** [comment]
It still sounds like parse order though. I would advise trying the `parse="inward"` parameter on the channel entries tag to see if that fixes it. Alternatively try using an embed; pass the Video URL to an embed with an embed parameter and render Antenna's embed code there.

**Comment by ashleymarchant** [comment]
Ok - first I tried simply adding parse="inward" to the channel entries tag which didn't seem to help. So I tried using stash to set a variable using this code:
`{exp:channel:entries channel="video" limit="1" parse="inward"}
{exp:stash:set name="newvideo"}{video_url}{/exp:stash:set}
{/exp:channel:entries}`

And replaced the code below to get the video:
`{if {exp:stash:not_empty name="newvideo"}}
    {exp:stash:get name="newvideo"}
        {exp:antenna url="{exp:stash:get name="newvideo"}" max_width="500" max_height="380"}
           {embed_code}    
        {/exp:antenna}
{/if}`

The template is still not rendering the video player. What should we try next?

**Comment by mrw** [comment]
You should give an embed a try.

**Comment by ashleymarchant** [comment]
Ok so the display template contains this code: `{embed="includes/vimeo-embed" id="{entry_id}"}`

And the embedded template has this code: `{exp:channel:entries channel="video" status="community|amasai|tsw|worship|public|sunday morning" limit="1" entry_id="{embed:id}"}
{exp:antenna url="{video_url}" max_width="500" max_height="380"}
           {embed_code}    
        {/exp:antenna}
{/exp:channel:entries}`

There still isnt anything showing up - I will admit I haven't done an embed for 3+ years since we started using stash so I might be doing it wrong?

**Comment by mrw** [comment]
Sorry, to be clear, I meant to *just* have antenna on the embed so you avoid potential parse order issues.

**Comment by ashleymarchant** [comment]
Ok so now the display template looks like this:
`{exp:channel:entries channel="video" limit="1" parse="inward"}
{embed="includes/vimeo-embed"}
{/exp:channel:entries}
`
and the embedded template contains this:
`{exp:antenna url="{video_url}" max_width="500" max_height="380"}
           {embed_code}    
        {/exp:antenna}`

Is this right?

**Comment by mrw** [comment]
Hi Ashley,

In general I'd do something like this:

```
{exp:channel:entries channel="video" limit="1"}
{embed="includes/vimeo-embed" video_url="{video_url}"}
{/exp:channel:entries}
```
And then in the embed:
```
{exp:antenna url="{embed:video_url}" max_width="500" max_height="380"}
{embed_code}
{/exp:antenna}
```
If that doesn't work then you'll want to check the output of your code a different way. Make sure you've followed the note in our README,

> NOTE For this to work with all urls please ensure that in Weblog/Channel -> Preferences, you have 'Automatically turn URLs and email addresses into links?' set to 'No'.

And do some other testing to see what's actually outputting. If Antenna is working when you hardcode the video URL, this isn't an Antenna issue; it's an output or parsing issue. I hope that helps!

**Comment by ashleymarchant** [comment]
: | Arg - so sorry. It was the channel preference setting the whole time. As soon as I changed it everything worked. Thank you for your patience.

**Comment by mrw** [comment]
Glad you figured it out!
