### ISSUE TITLE
{video_highres} is not highres for Vimeo

### ISSUE THREAD

**Issue by shbchk** [vector/Antenna#37]
Hi there! Thanks for this very useful add-on! 

Found an issue. 

{video_highres} variable for Vimeo returns not highest possible resolution

For example, for this video: https://vimeo.com/523796454 {video_highres} variable returns this image (640 px): https://i.vimeocdn.com/video/1265722798-d291906fd3e6c958815e0e09b15d5cf08811fc74e2f7fed25_640

And for this video: https://vimeo.com/433579869 {video_highres} variable returns this image (295 px): https://i.vimeocdn.com/video/1216245799-32c3a01f036fbc1d04bbaedd63ff65a4dffd647404273dcdd4beabdf0ba739dd-d_295x166

**Comment by mrw** [comment]
Hi @shbchk! Unfortunately we're not updating Antenna at the moment. You're welcome to submit a pull request with a fix for this and a version bump if you'd like though. While I can't promise any specific timeline or action, we'd consider reviewing and merging that.

**Comment by shbchk** [comment]
That's unfortunate, I am not a dev :) But thanks anyway!
