### ISSUE TITLE
'maxresdefault' thumbnail not on all YouTube videos anymore

### ISSUE THREAD

**Issue by ttmwebdesign** [vector/Antenna#38]
Just a quick heads up, it seems that YouTube isn't creating a 'maxresdefault' thumbnail for all videos. I don't know what the magic is in YT world to decide when one is created or not. I've seen a video posted three months ago that has it, but there's another from a year ago that _does not._ 

However, there do seem to be 'maxres1.jpg' thumbnails, on videos that otherwise have a 'hqdefault' type of thumbnail vs. a maxresdefault*. I saw in the Antenna code that it str_replace's hqdefault -> maxresdefault, and this will not work if YT didn't create a maxresdefault on hqdefault videos. The 'maxresdefault' jpg _does_ exist, but... it's just the ugly, _really_ tiny default YT thumbnail and not really from the actual video. See: https://i.ytimg.com/vi/p3cIBqRVfnY/maxresdefault.jpg as an example.

Replacing 'maxresdefault' witih 'maxres1' results in a good Thumbnail, but there's a catch here, too. *It depends on how old the video is apparently. Super old ones (10+ years, like the sample one above), may not have that 'maxres1' version. It does have hqdefault, so in the case of super old videos, str_replace'ing hqdefault with maxresdefault is not a good option.

For our client's particular case, their videos are newer, so I was able to hack line 224 of pi.antenna.php to swap out 'maxresdefault' for 'maxres1', and it will work for them. But this won't work in all cases if they happen to be old videos.

I guess I am curious if it would be possible to create a simple settings page to be able to define whether one wants the 'hqdefault' option to be replaced (old videos, probably not), and if at all, with what? In our client's case, hqdefault is still pretty small and can be grainy if it's forced to be bigger, but 'maxres1' is much better as it's 1280px wide.

I don't know enough of plugin/addon development to be able to PR the idea above (settings page), or I would. I could PR the hack I did, but as noted that only works for newer videos, and even then I only know that it seems to be working in our case. I don't know if it would work for most videos or not, and what the cutoff is in video age for these bigger ones, "maxres1", to exist as a substitute for 'maxresdefault'.

Thoughts? Thanks!

**Comment by mrw** [comment]
Hi @ttmwebdesign! Unfortunately we're not updating Antenna anymore. I'm glad your adjustment was able to help!
